# Generated by Django 5.0.6 on 2025-10-09 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0047_alter_fabric_intransit_alter_fabric_reserve'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('completed', 'Завершена'), ('canceled', 'Отменена')], default='new', max_length=50, verbose_name='Статус')),
                ('plan_date', models.DateTimeField(blank=True, null=True, verbose_name='Плановая дата отгрузки')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Отгрузка',
                'verbose_name_plural': 'Отгрузки',
            },
        ),
        migrations.CreateModel(
            name='ShipmentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255, verbose_name='Комментарий')),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_shipments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipment.shipment')),
            ],
            options={
                'verbose_name': 'Комментарий к отгрузке',
                'verbose_name_plural': 'Комментарии к отгрузкам',
                'ordering': ['-add_date'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('order_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_rows', to='core.orderproduct', verbose_name='Заказанная позиция')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='shipment.shipment')),
            ],
            options={
                'verbose_name': 'Позиция отгрузки',
                'verbose_name_plural': 'Позиции отгрузки',
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1, verbose_name='Номер экземпляра')),
                ('is_reserved', models.BooleanField(default=False, verbose_name='Зарезервирован')),
                ('reserver_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID Зарезервированного товара')),
                ('reserved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Проверен')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_shipments', to=settings.AUTH_USER_MODEL)),
                ('reserved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_shipments', to=settings.AUTH_USER_MODEL)),
                ('shipment_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipment.shipmentrow')),
            ],
            options={
                'verbose_name': 'Экземпляр позиции',
                'verbose_name_plural': 'Экземпляры позиций',
            },
        ),
    ]
