# Generated by Django 5.0.6 on 2025-10-09 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_shipment_created_at_shipment_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentitem',
            name='shipment_row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shipment.shipmentrow'),
        ),
    ]
