# Generated by Django 5.0.6 on 2025-10-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0003_alter_shipmentitem_shipment_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentitem',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер экземпляра'),
        ),
        migrations.AlterUniqueTogether(
            name='shipmentitem',
            unique_together={('shipment_row', 'number')},
        ),
    ]
