# Generated by Django 5.0.6 on 2025-10-09 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_fabric_intransit_alter_fabric_reserve'),
        ('shipment', '0004_alter_shipmentitem_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shipmentitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='order_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipment_items', to='core.orderproduct', verbose_name='Заказанная позиция'),
        ),
        migrations.AlterField(
            model_name='shipmentcomment',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_comments', to='shipment.shipment'),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_shipments', to=settings.AUTH_USER_MODEL, verbose_name='Проверил'),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='shipment_row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shipment.shipmentrow', verbose_name='Позиция отгрузки'),
        ),
        migrations.AlterUniqueTogether(
            name='shipmentitem',
            unique_together={('order_product', 'number')},
        ),
    ]
