# Generated by Django 5.0.6 on 2026-04-07 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0050_product_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiPlanConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_prompt', models.TextField(blank=True, default='', verbose_name='Базовый промпт')),
                ('ai_summary', models.TextField(blank=True, default='', verbose_name='AI сводка')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Конфигурация AI плана',
                'verbose_name_plural': 'Конфигурация AI плана',
            },
        ),
        migrations.CreateModel(
            name='DepartmentWorkers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50, unique=True, verbose_name='Цех')),
                ('workers_count', models.IntegerField(default=1, verbose_name='Количество рабочих')),
            ],
            options={
                'verbose_name': 'Рабочие в цехе',
                'verbose_name_plural': 'Рабочие в цехах',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип изделия',
                'verbose_name_plural': 'Типы изделий',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AiPlanEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_weight', models.IntegerField(default=50, verbose_name='Важность (0-100)')),
                ('sort_position', models.IntegerField(default=0, verbose_name='Позиция в очереди')),
                ('ai_comment', models.TextField(blank=True, default='', verbose_name='AI комментарий')),
                ('feedback', models.TextField(blank=True, default='', verbose_name='Обратная связь')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('order_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_plan_entry', to='core.orderproduct', verbose_name='Позиция заказа')),
            ],
            options={
                'verbose_name': 'AI запись плана',
                'verbose_name_plural': 'AI записи плана',
            },
        ),
        migrations.CreateModel(
            name='ProductionNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Обивка', 'Обивка'), ('Крой', 'Крой'), ('Пила', 'Пила'), ('Сборка', 'Сборка'), ('Пошив', 'Пошив'), ('Поролон', 'Поролон'), ('Лазер', 'Лазер'), ('Массив', 'Массив')], max_length=50, verbose_name='Цех')),
                ('hours_per_unit', models.FloatField(default=0, verbose_name='Часов на 1 шт')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='norms', to='plan.producttype', verbose_name='Тип изделия')),
            ],
            options={
                'verbose_name': 'Норматив производства',
                'verbose_name_plural': 'Нормативы производства',
                'unique_together': {('product_type', 'department')},
            },
        ),
    ]
