# Generated by Django 5.0.6 on 2026-04-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0008_aiplanconfig_weight_k_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionnorm',
            name='department',
            field=models.CharField(max_length=50, verbose_name='Цех'),
        ),
        migrations.AlterField(
            model_name='productnormoverride',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
