version: "3.8"

services:
  postgres:
    build: ./services/postgres_db
    container_name: postgres_db_eq
    expose:
      - "5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env.docker.prod

  django_app:
    build:
      context: ./django_app
      dockerfile: Dockerfile
    container_name: django_app_eq
    restart: always
    depends_on:
      - redis
      - postgres
    ports:
      - "8000:8000"
    env_file:
      - .env.docker.prod
    volumes:
      - ./django_app/media/:/app/media
    command: >
      sh -c "uvicorn django_app.asgi:application --host 0.0.0.0 --port 8000"

  pgadmin:
    build:
      context: ./services/pgadmin
      dockerfile: Dockerfile
    container_name: pgadmin_eq
    restart: always
    depends_on:
      - postgres
    ports:
      - "5050:80"
    env_file:
      - .env.docker.prod
    volumes:
      - ./services/pgadmin/PGADMINDATA:/var/lib/pgadmin

  db-admin:
    image: adminer:4.8.1
    ports:
      - "8080:8080"
    restart: always

  redis:
    container_name: redis_eq
    build: ./services/redis
    ports:
      - "6379:6379"
    restart: always

  nginx:
    container_name: nginx_eq
    build: ./services/nginx
    restart: always
    depends_on:
      - django_app
    volumes:
      - ./new_react/build/:/usr/share/nginx/html
      - ./django_app/media/:/usr/share/nginx/html/media
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    env_file:
      - .env.docker.prod

  celery_worker:
    build:
      context: ./django_app
      dockerfile: Dockerfile
    container_name: celery_worker_eq
    restart: always
    volumes:
      - ./django_app/media/:/app/media
    depends_on:
      - django_app
      - postgres
    ports:
      - "58231"
    command: celery -A django_app worker -l info
    env_file:
      - .env.docker.prod

  celery_beat:
    build:
      context: ./django_app
      dockerfile: Dockerfile
    container_name: celery_beat_eq
    restart: always
    depends_on:
      - django_app
      - postgres
    volumes:
      - ./django_app/media/:/app/media
    ports:
      - "58232"
    command: celery -A django_app beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env.docker.prod


volumes:
  db_data:
    driver: local