version: "3.8"

services:
  postgres_db:
    build: ./postgres_db
    container_name: postgres_db
    restart: always
    volumes:
      - ./postgres_db/PGDATA:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

#  django_app:
#    build:
#      context: ./django_app
#      dockerfile: Dockerfile
#    container_name: django_app
#    restart: always
#    depends_on:
#      - postgres_db
#      - redis
#    ports:
#      - "8000:8000"
#    env_file:
#      - .env
#    command: >
#      sh -c "python manage.py makemigrations &&
#             python manage.py migrate &&
#             python manage.py runserver 0.0.0.0:8000"


#  pgadmin:
#    build:
#      context: ./pgadmin
#      dockerfile: Dockerfile
#    container_name: pgadmin
#    restart: always
#    depends_on:
#      - postgres_db
#    ports:
#      - "5050:80"
#    env_file:
#      - ./.env
#    volumes:
#      - ./pgadmin/PGADMINDATA:/var/lib/pgadmin

  redis:
    container_name: redis
    build: ./redis
    restart: always
    ports:
      - "6379:6379"

#  nginx:
#    container_name: nginx
#    build: ./nginx
#    restart: always
#    depends_on:
#      - django_app
#    volumes:
#      - ./react_app/build/:/usr/share/nginx/html
#    ports:
#      - "80:80"
