services:
  server:
    build:
      context: ./django_app/
      dockerfile: DockerfileDev
    container_name: server
    restart: always
    volumes:
      - ./django_app:/app
    depends_on:
      - pg
      - redis
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: >
      sh -c "python3 manage.py runserver 0.0.0.0:8000"

  pg:
    build: services/postgres_db
    container_name: pg
    restart: always
    volumes:
      - ./services/postgres_db/PGDATA:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

  pgadmin:
    build:
      context: ./services/pgadmin
      dockerfile: Dockerfile
    container_name: pgadmin
    restart: always
    depends_on:
      - pg
    ports:
      - "5050:80"
    env_file:
      - .env
    volumes:
      - ./services/pgadmin/PGADMINDATA:/var/lib/pgadmin

  redis:
    container_name: redis
    build: services/redis
    restart: always
    ports:
      - "6379:6379"

  nginx:
    container_name: nginx
    build: ./services/nginx
    restart: always
    depends_on:
      - server
    volumes:
      - ./django_app/media/:/usr/share/nginx/html/media
      - ./services/nginx/nginx.dev.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    env_file:
      - .env
