# Generated by Django 4.1.7 on 2023-05-04 10:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, verbose_name='Порядковый номер наряда')),
                ('date_completion', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('notes', models.CharField(blank=True, max_length=250, verbose_name='Заметки')),
                ('status', models.CharField(choices=[('await', 'Ожидает назначения'), ('in_work', 'В работе'), ('ready', 'Выполнен'), ('cancelled', 'Отменен')], default='await', max_length=50, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Наряд',
                'verbose_name_plural': 'Наряды',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='API ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название ткани')),
                ('image_filename', models.CharField(blank=True, max_length=120, null=True, verbose_name='Имя файла')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/products/', verbose_name='Ссылка на изображение')),
            ],
            options={
                'verbose_name': 'Ткань',
                'verbose_name_plural': 'Ткани',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='API ID')),
                ('number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Номер заказа')),
                ('project', models.CharField(blank=True, max_length=250, verbose_name='Проект')),
                ('planned_date', models.DateField(blank=True, null=True, verbose_name='Произв. (пл. Дата):')),
                ('urgency', models.SmallIntegerField(default=3, verbose_name='Срочность')),
                ('comment_base', models.TextField(blank=True, verbose_name='Коммент. (каркас):')),
                ('comment_case', models.TextField(blank=True, verbose_name='Коммент. (чехол):')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_id', models.CharField(max_length=50, null=True, unique=True, verbose_name='ID Серии')),
                ('status', models.CharField(choices=[('0', 'Ожидает'), ('1', 'Изготовлен')], default='0', max_length=50, verbose_name='Статус')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена')),
                ('urgency', models.SmallIntegerField(default=3, verbose_name='Срочность')),
                ('comment_base', models.TextField(blank=True, verbose_name='Коммент. (каркас):')),
                ('comment_case', models.TextField(blank=True, verbose_name='Коммент. (чехол):')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказов',
                'ordering': ['urgency', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'Новый'), ('2', 'Ожидает назначения'), ('3', 'В разработке'), ('4', 'Разработан')], default='1', max_length=25, verbose_name='Статус')),
                ('product_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='API ID')),
                ('name', models.CharField(blank=True, max_length=250, unique=True, verbose_name='Наименование официальное')),
                ('name_internal', models.CharField(blank=True, max_length=250, verbose_name='Наименование внутреннее')),
                ('type', models.CharField(choices=[('product', 'Товар'), ('variant', 'Модификация')], default='product', max_length=7, verbose_name='Товар/Модификация')),
                ('group', models.CharField(blank=True, max_length=250, verbose_name='Группа товара')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание товара')),
            ],
            options={
                'verbose_name': 'Изделие',
                'verbose_name_plural': 'Изделия',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.PositiveIntegerField(default=0, verbose_name='План время этапа (минут)')),
            ],
            options={
                'verbose_name': 'Этап производства',
                'verbose_name_plural': 'Этапы производства',
            },
        ),
        migrations.CreateModel(
            name='ProductionStepTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff', models.IntegerField(default=0, verbose_name='Производственный тариф')),
                ('confirmation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата/Время подтверждения')),
            ],
            options={
                'verbose_name': 'Тарификация этапа',
                'verbose_name_plural': 'Тарификации этапов',
            },
        ),
        migrations.CreateModel(
            name='TechnologicalProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('schema', models.JSONField(default=None, verbose_name='Схема')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/processes/', verbose_name='Изображение схемы процесса')),
            ],
            options={
                'verbose_name': 'Технологический процесс',
                'verbose_name_plural': 'Технологические процессы',
            },
        ),
        migrations.CreateModel(
            name='TechProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_filename', models.CharField(blank=True, max_length=120, null=True, verbose_name='Имя файла')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/products/', verbose_name='Ссылка на изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_pictures', to='core.product')),
            ],
            options={
                'verbose_name': 'Изображение изделия',
                'verbose_name_plural': 'Изображения изделий',
            },
        ),
    ]
