# Generated by Django 4.1.7 on 2023-03-31 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Новый', 'Новый'), ('Ожидает назначения', 'Ожидает назначения'), ('В разработке', 'В разработке'), ('Разработан', 'Разработан')], default='Новый', max_length=25, verbose_name='Статус')),
                ('product_ID', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='API ID')),
                ('name', models.CharField(blank=True, max_length=250, unique=True, verbose_name='Наименование официальное')),
                ('name_internal', models.CharField(blank=True, max_length=250, verbose_name='Наименование внутреннее')),
                ('type', models.CharField(choices=[('product', 'Товар'), ('variant', 'Модификация')], default='product', max_length=7, verbose_name='Товар/Модификация')),
                ('group', models.CharField(blank=True, max_length=250, verbose_name='Группа товара')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание товара')),
                ('end_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.department', verbose_name='Конечный отдел производства')),
                ('technological_process_confirmed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Технологический процесс подтвердил')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(verbose_name='Ссылка на изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_pictures', to='core.product')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товара',
            },
        ),
    ]
