# Generated by Django 4.1.7 on 2023-05-04 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionsteptariff',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_step_tariffs', to=settings.AUTH_USER_MODEL, verbose_name='Тарификацию утвердил'),
        ),
        migrations.AddField(
            model_name='productionsteptariff',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_step_tariffs', to='staff.department', verbose_name='Отдел'),
        ),
        migrations.AddField(
            model_name='productionsteptariff',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_step_tariffs', to='core.product', verbose_name='Изделие'),
        ),
        migrations.AddField(
            model_name='productionstep',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.department', verbose_name='production_steps'),
        ),
        migrations.AddField(
            model_name='productionstep',
            name='next_step',
            field=models.ManyToManyField(blank=True, related_name='production_steps', to='core.productionstep', verbose_name='Последующие этапы'),
        ),
        migrations.AddField(
            model_name='productionstep',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_steps', to='core.product'),
        ),
        migrations.AddField(
            model_name='productionstep',
            name='production_step_tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_steps', to='core.productionsteptariff', verbose_name='Тарификация'),
        ),
        migrations.AddField(
            model_name='product',
            name='technological_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.technologicalprocess', verbose_name='Технологический процесс'),
        ),
        migrations.AddField(
            model_name='product',
            name='technological_process_confirmed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Технологический процесс подтвердил'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='main_fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_products_main', to='core.fabric', verbose_name='Ткань основа'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='core.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='core.product', verbose_name='Изделие'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='second_fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_products_second', to='core.fabric', verbose_name='Ткань компаньон'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='third_fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_products_third', to='core.fabric', verbose_name='Ткань дополнительная'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='staff.department', verbose_name='Отдел'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_executor', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='inspector',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_inspector', to=settings.AUTH_USER_MODEL, verbose_name='Проверяющий'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='order_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.orderproduct', verbose_name='Позиция заказа'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='core.productionsteptariff', verbose_name='Тарификация'),
        ),
    ]
