# Generated by Django 4.1.7 on 2023-03-31 14:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название ткани')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Ссылка на изображение')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Ткань',
                'verbose_name_plural': 'Ткани',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='API ID')),
                ('number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Номер заказа')),
                ('project', models.CharField(blank=True, max_length=250, verbose_name='Проект')),
                ('planned_date', models.DateField(blank=True, null=True, verbose_name='Произв. (пл. Дата):')),
                ('urgency', models.SmallIntegerField(default=3, verbose_name='Срочность')),
                ('comment_base', models.TextField(blank=True, verbose_name='Коммент. (каркас):')),
                ('comment_case', models.TextField(blank=True, verbose_name='Коммент. (чехол):')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name': 'Изделие', 'verbose_name_plural': 'Изделия'},
        ),
        migrations.AlterModelOptions(
            name='productpicture',
            options={'verbose_name': 'Изображение изделия', 'verbose_name_plural': 'Изображения изделий'},
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('1', 'Новый'), ('2', 'Ожидает назначения'), ('3', 'В разработке'), ('4', 'Разработан')], default='1', max_length=25, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_id', models.CharField(max_length=50, null=True, unique=True, verbose_name='ID Серии')),
                ('status', models.CharField(choices=[('0', 'Ожидает'), ('1', 'Изготовлен')], default='0', max_length=50, verbose_name='Статус')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена')),
                ('urgency', models.SmallIntegerField(default=3, verbose_name='Срочность')),
                ('comment_base', models.TextField(blank=True, verbose_name='Коммент. (каркас):')),
                ('comment_case', models.TextField(blank=True, verbose_name='Коммент. (чехол):')),
                ('main_fabric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_products_main', to='core.fabric', verbose_name='Ткань основа')),
                ('order', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='core.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='core.product', verbose_name='Изделие')),
                ('second_fabric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_products_second', to='core.fabric', verbose_name='Ткань компаньон')),
                ('third_fabric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_products_third', to='core.fabric', verbose_name='Ткань дополнительная')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказов',
                'ordering': ['urgency', 'order', 'id'],
            },
        ),
    ]
