# Generated by Django 4.1.7 on 2023-06-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='moment',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата документа'),
        ),
    ]
