# Generated by Django 4.1.7 on 2023-03-31 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_department_piecework_wages_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_fabric_order_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologicalProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('schema', models.JSONField(default=None, verbose_name='Схема')),
                ('image', models.ImageField(upload_to='images/processes/', verbose_name='Ссылка на изображение')),
            ],
            options={
                'verbose_name': 'Технологический процесс',
                'verbose_name_plural': 'Технологические процессы',
            },
        ),
        migrations.AlterField(
            model_name='fabric',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/', verbose_name='Ссылка на изображение'),
        ),
        migrations.AlterField(
            model_name='productpicture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/', verbose_name='Ссылка на изображение'),
        ),
        migrations.CreateModel(
            name='ProductionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.PositiveIntegerField(default=0, verbose_name='План время этапа (минут)')),
                ('tax', models.IntegerField(default=0, verbose_name='Производственный тариф')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.department', verbose_name='production_steps')),
                ('next_step', models.ManyToManyField(blank=True, to='core.productionstep', verbose_name='Последующие этапы')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_steps', to='core.product')),
            ],
            options={
                'verbose_name': 'Этап производства',
                'verbose_name_plural': 'Этапы производства',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, verbose_name='Порядковый номер наряда')),
                ('date_completion', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('notes', models.CharField(blank=True, max_length=250, verbose_name='Заметки')),
                ('status', models.CharField(choices=[('await', 'Ожидает назначения'), ('in_work', 'В работе'), ('ready', 'Выполнен'), ('cancelled', 'Отменен')], default='await', max_length=50, verbose_name='Статус')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Тариф')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='staff.department', verbose_name='Отдел')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_executor', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('inspector', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_inspector', to=settings.AUTH_USER_MODEL, verbose_name='Проверяющий')),
                ('order_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='core.orderproduct', verbose_name='Позиция заказа')),
            ],
            options={
                'verbose_name': 'Наряд',
                'verbose_name_plural': 'Наряды',
                'ordering': ['id'],
            },
        ),
    ]
