# Generated by Django 4.1.7 on 2023-03-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_technologicalprocess_alter_fabric_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionstep',
            name='next_step',
            field=models.ManyToManyField(related_name='production_steps', to='core.productionstep', verbose_name='Последующие этапы'),
        ),
        migrations.AlterField(
            model_name='technologicalprocess',
            name='image',
            field=models.ImageField(upload_to='images/processes/', verbose_name='Изображение схемы процесса'),
        ),
    ]
