# Generated by Django 4.1.7 on 2023-06-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_moment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='moment',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата документа'),
        ),
    ]
