# Generated by Django 4.1.7 on 2023-03-31 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_productionstep_next_step_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='end_department',
        ),
        migrations.AddField(
            model_name='product',
            name='technological_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.technologicalprocess', verbose_name='Технологический процесс'),
        ),
    ]
