# Generated by Django 4.1.7 on 2023-06-15 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('core', '0004_alter_order_moment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('number', 'order_product', 'department')},
        ),
    ]
