# Generated by Django 4.1.7 on 2023-07-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_assignment_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productpicture',
            options={'ordering': ['-id'], 'verbose_name': 'Изображение изделия', 'verbose_name_plural': 'Изображения изделий'},
        ),
        migrations.AddField(
            model_name='productionstep',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Этап задействован в производстве'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='date_completion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата готовности'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('await', 'Ожидает назначения'), ('in_work', 'В работе'), ('ready', 'Выполнен'), ('cancelled', 'Отменен')], default='await', max_length=50, verbose_name='Статус'),
        ),
    ]
