# Generated by Django 4.1.7 on 2023-04-03 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_product_end_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabric',
            name='quantity',
        ),
    ]
