# Generated by Django 4.1.7 on 2023-07-26 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('core', '0006_alter_productpicture_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productionstep',
            unique_together={('department', 'product')},
        ),
    ]
