# Generated by Django 4.1.7 on 2023-04-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_fabric_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_ID',
            new_name='product_id',
        ),
        migrations.AlterField(
            model_name='productionstep',
            name='next_step',
            field=models.ManyToManyField(blank=True, related_name='production_steps', to='core.productionstep', verbose_name='Последующие этапы'),
        ),
    ]
