# Generated by Django 4.1.7 on 2023-08-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_productionstep_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/thumbnails/', verbose_name='Миниатюра'),
        ),
        migrations.AddField(
            model_name='productpicture',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/thumbnails/', verbose_name='Миниатюра'),
        ),
    ]
