# Generated by Django 4.1.7 on 2023-04-07 11:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_product_id_product_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='fabric_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='API ID'),
        ),
    ]
