# Generated by Django 4.1.7 on 2023-08-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_fabric_thumbnail_productpicture_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric',
            name='image_filename',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Имя файла'),
        ),
        migrations.AlterField(
            model_name='productpicture',
            name='image_filename',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Имя файла'),
        ),
    ]
