# Generated by Django 4.1.7 on 2023-04-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_fabric_fabric_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpicture',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Имя файла'),
        ),
    ]
