# Generated by Django 4.1.7 on 2023-08-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_fabric_image_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric',
            name='image',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='images/products/', verbose_name='Ссылка на изображение'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='images/products/thumbnails/', verbose_name='Миниатюра'),
        ),
    ]
