# Generated by Django 4.1.7 on 2023-04-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_productpicture_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productpicture',
            old_name='name',
            new_name='image_filename',
        ),
        migrations.AddField(
            model_name='fabric',
            name='image_filename',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Имя файла'),
        ),
    ]
