# Generated by Django 4.1.7 on 2023-04-10 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_employee_departments'),
        ('core', '0010_rename_name_productpicture_image_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='staff.department', verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='order_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.orderproduct', verbose_name='Позиция заказа'),
        ),
    ]
