# Generated by Django 4.1.7 on 2023-08-18 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_alter_fabric_image_alter_fabric_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionsteptariff',
            name='proposed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_step_proposed_tariffs', to=settings.AUTH_USER_MODEL, verbose_name='Тарификацию утвердил'),
        ),
        migrations.AddField(
            model_name='productionsteptariff',
            name='proposed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата/Время предложения'),
        ),
        migrations.AddField(
            model_name='productionsteptariff',
            name='proposed_tariff',
            field=models.IntegerField(default=0, verbose_name='Предложенный тариф'),
        ),
        migrations.AlterField(
            model_name='productionsteptariff',
            name='confirmation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата/Время утверждения'),
        ),
        migrations.AlterField(
            model_name='productionsteptariff',
            name='tariff',
            field=models.IntegerField(default=0, verbose_name='Утвержденный тариф'),
        ),
    ]
