# Generated by Django 4.1.7 on 2023-08-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_productionsteptariff_proposed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='inspect_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата визирования'),
        ),
    ]
