# Generated by Django 4.1.7 on 2024-02-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_assignment_inspect_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='appointment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата взятия в работу'),
        ),
    ]
