# Generated by Django 4.1.7 on 2024-02-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_assignment_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='ready_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата готовности'),
        ),
    ]
