# Generated by Django 4.1.7 on 2024-02-27 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_assignment_ready_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='ready_date',
        ),
    ]
