# Generated by Django 4.1.7 on 2024-02-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_assignment_ready_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='appointed_by_boss',
            field=models.BooleanField(blank=True, default=False, verbose_name='Назначен бригадиром'),
        ),
    ]
