# Generated by Django 4.1.7 on 2024-02-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_assignment_appointed_by_boss'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='plane_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='План дата готовности'),
        ),
    ]
