# Generated by Django 4.1.7 on 2024-04-26 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0017_assignment_plane_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='comment_base',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='comment_case',
        ),
        migrations.CreateModel(
            name='OrderProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('important', models.BooleanField(default=False, verbose_name='Важное')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('text', models.CharField(max_length=255, verbose_name='Комментарий')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('order_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orderproduct', verbose_name='Позиция заказа')),
            ],
            options={
                'verbose_name': 'Комментарий к ПЗ',
                'verbose_name_plural': 'Комментарии к ПЗ',
                'ordering': ['id'],
            },
        ),
    ]
