# Generated by Django 4.1.7 on 2024-05-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_orderproduct_comment_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='inner_number',
            field=models.CharField(blank=True, max_length=250, verbose_name='Вх. заказ (№):'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', 'В работе'), ('1', 'Изготовлен')], default='0', max_length=50, verbose_name='Статус'),
        ),
    ]
