# Generated by Django 4.1.7 on 2024-05-27 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0019_order_inner_number_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproductcomment',
            options={'ordering': ['-important', '-add_date'], 'verbose_name': 'Комментарий к ПЗ', 'verbose_name_plural': 'Комментарии к ПЗ'},
        ),
        migrations.AlterField(
            model_name='productionsteptariff',
            name='proposed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_step_proposed_tariffs', to=settings.AUTH_USER_MODEL, verbose_name='Тарификацию предложил'),
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('production_step', 'Тарификация этапа производства')], default='production_step', max_length=50, verbose_name='Статус')),
                ('amount', models.IntegerField(default=0, verbose_name='Сумма')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('comment', models.CharField(blank=True, max_length=250, null=True, verbose_name='Комментарий')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='new_tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_set', to='core.tariff', verbose_name='Тариф (новый)'),
        ),
        migrations.AddField(
            model_name='productionstep',
            name='confirmed_tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_steps_confirmed', to='core.tariff', verbose_name='Утвержденный тариф'),
        ),
        migrations.AddField(
            model_name='productionstep',
            name='proposed_tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_steps_proposed', to='core.tariff', verbose_name='Предложенный тариф'),
        ),
    ]
