# Generated by Django 4.1.7 on 2024-05-28 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_orderproductcomment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='type',
        ),
    ]
