# Generated by Django 4.1.7 on 2024-05-28 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_tariff_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='add_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 28, 16, 57, 55, 37223), verbose_name='Дата добавления'),
        ),
    ]
