# Generated by Django 5.0.6 on 2024-06-15 07:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_tariff_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='add_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата добавления'),
        ),
    ]
