# Generated by Django 5.0.6 on 2024-06-24 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_tariff_add_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionstep',
            name='production_step_tariff',
        ),
    ]
