# Generated by Django 5.0.6 on 2024-06-25 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_productionstep_production_step_tariff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='tariff',
        ),
        migrations.DeleteModel(
            name='ProductionStepTariff',
        ),
    ]
