# Generated by Django 5.0.6 on 2024-07-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_assignment_tariff_delete_productionsteptariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assembled',
            field=models.BooleanField(blank=True, default=True, verbose_name='Укомплектован'),
        ),
    ]
