# Generated by Django 5.0.6 on 2024-08-05 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_assignment_assembled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentCoExecutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='Сумма')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.assignment')),
                ('co_executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Соисполнитель',
                'verbose_name_plural': 'Соисполнители',
                'unique_together': {('assignment', 'co_executor')},
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='co_executors',
            field=models.ManyToManyField(related_name='co_executed_assignments', through='core.AssignmentCoExecutor', to=settings.AUTH_USER_MODEL, verbose_name='Соисполнители'),
        ),
    ]
