# Generated by Django 5.0.6 on 2024-08-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_assignmentcoexecutor_assignment_co_executors'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Вознаграждение'),
        ),
    ]
