# Generated by Django 5.0.6 on 2024-08-21 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_assignment_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='co_executors',
        ),
        migrations.AlterField(
            model_name='assignmentcoexecutor',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_executors', to='core.assignment'),
        ),
        migrations.AlterField(
            model_name='assignmentcoexecutor',
            name='co_executor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_executed_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
