# Generated by Django 5.0.6 on 2024-09-17 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_tariff_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionStepComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255, verbose_name='Комментарий')),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_step_comment_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('production_step', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_step_comments', to='core.productionstep', verbose_name='Этап производства')),
            ],
            options={
                'verbose_name': 'Комментарий к сделке',
                'verbose_name_plural': 'Комментарии к сделкам',
                'ordering': ['-add_date'],
            },
        ),
    ]
