# Generated by Django 5.0.6 on 2024-09-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_productionstepcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='tariffication_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата тарифицирования'),
        ),
    ]
