# Generated by Django 5.0.6 on 2024-12-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_assignment_tariffication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentcoexecutor',
            name='wages_amount',
            field=models.IntegerField(default=0, verbose_name='Сумма'),
        ),
    ]
