# Generated by Django 5.0.6 on 2025-05-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_assignmentcoexecutor_wages_amount'),
        ('staff', '0017_employee_kpd'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionstep',
            name='next_steps',
            field=models.ManyToManyField(blank=True, related_name='production_steps', to='staff.department', verbose_name='Последующие этапы'),
        ),
        migrations.AlterField(
            model_name='productionstep',
            name='next_step',
            field=models.ManyToManyField(blank=True, related_name='prod_steps', to='core.productionstep', verbose_name='Последующие этапы'),
        ),
    ]
