# Generated by Django 5.0.6 on 2025-05-08 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_productionstep_next_steps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionstep',
            name='next_step',
        ),
    ]
