# Generated by Django 5.0.6 on 2025-08-14 10:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_product_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Обновлен в API'),
        ),
    ]
