# Generated by Django 5.0.6 on 2025-08-20 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_fabric_updated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='last_print_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_print', to=settings.AUTH_USER_MODEL, verbose_name='Последний напечатал'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='last_print_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последней печати'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='print_count',
            field=models.IntegerField(default=0, verbose_name='Напечатан раз'),
        ),
    ]
