# Generated by Django 5.0.6 on 2025-08-28 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_assignment_last_print_by_assignment_last_print_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric',
            name='image',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='images/fabrics/', verbose_name='Ссылка на изображение'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='images/fabrics/thumbnails/', verbose_name='Миниатюра'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='main_fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_products_main', to='core.fabric', verbose_name='Ткань основа'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='second_fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_products_second', to='core.fabric', verbose_name='Ткань компаньон'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='third_fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_products_third', to='core.fabric', verbose_name='Ткань дополнительная'),
        ),
    ]
