# Generated by Django 5.0.6 on 2025-08-28 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_fabric_image_alter_fabric_thumbnail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_filename', models.CharField(blank=True, max_length=240, null=True, verbose_name='Имя файла')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/fabrics/', verbose_name='Ссылка на изображение')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images/fabrics/thumbnails/', verbose_name='Миниатюра')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabric_pictures', to='core.fabric')),
            ],
            options={
                'verbose_name': 'Изображение ткани',
                'verbose_name_plural': 'Изображения тканей',
                'ordering': ['-id'],
            },
        ),
    ]
