# Generated by Django 5.0.6 on 2025-08-28 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_fabricpicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabric',
            name='image',
        ),
        migrations.RemoveField(
            model_name='fabric',
            name='image_filename',
        ),
        migrations.RemoveField(
            model_name='fabric',
            name='thumbnail',
        ),
    ]
