# Generated by Django 5.0.6 on 2025-08-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_remove_fabric_image_remove_fabric_image_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='barcode',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Штрихкод'),
        ),
        migrations.AddField(
            model_name='fabric',
            name='intransit',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Остаток'),
        ),
        migrations.AddField(
            model_name='fabric',
            name='is_actual',
            field=models.BooleanField(default=False, verbose_name='Актуальность'),
        ),
        migrations.AddField(
            model_name='fabric',
            name='quantity',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Остаток'),
        ),
        migrations.AddField(
            model_name='fabric',
            name='reserve',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Остаток'),
        ),
    ]
