# Generated by Django 5.0.6 on 2025-09-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_fabric_barcode_fabric_intransit_fabric_is_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='shipped',
            field=models.FloatField(default=0, verbose_name='Отгружено'),
        ),
    ]
