# Generated by Django 5.0.6 on 2025-09-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_orderproduct_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='sort_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата сортировки'),
        ),
    ]
