# Generated by Django 5.0.6 on 2025-09-15 16:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_assignment_sort_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.UUIDField(blank=True, null=True, verbose_name='API ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='AgentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование тега')),
            ],
            options={
                'verbose_name': 'Тег клиента',
                'verbose_name_plural': 'Теги клиента',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Обновлен в API'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, verbose_name='API order ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.agent'),
        ),
        migrations.AddField(
            model_name='agent',
            name='tags',
            field=models.ManyToManyField(related_name='clients', to='core.agenttag'),
        ),
    ]
