# Generated by Django 5.0.6 on 2025-09-30 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_agent_agenttag_order_owner_order_updated_and_more'),
        ('staff', '0022_employee_api_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologicalprocess',
            name='final_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.department', verbose_name='Конечный отдел готовности изделия'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('0', 'Ожидает'), ('1', 'Изготовлен'), ('2', 'Отменен')], default='0', max_length=50, verbose_name='Статус'),
        ),
    ]
