# Generated by Django 5.0.6 on 2025-10-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_technologicalprocess_final_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric',
            name='intransit',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='В пути'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='reserve',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Резерв'),
        ),
    ]
