# Generated by Django 5.0.6 on 2025-12-04 09:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_fabric_intransit_alter_fabric_reserve'),
        ('staff', '0022_employee_api_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='urgency',
            field=models.SmallIntegerField(choices=[(1, 'Высокая'), (2, 'Средняя'), (3, 'Низкая')], default=3, verbose_name='Срочность'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['order_product', 'department', 'status'], name='core_assign_order_p_5820b1_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['executor', 'status'], name='core_assign_executo_43989f_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['inspector', 'status'], name='core_assign_inspect_ca2159_idx'),
        ),
    ]
