# Generated by Django 5.0.6 on 2026-01-28 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_assignment_urgency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='tariff_checked',
            field=models.BooleanField(default=False, verbose_name='Тариф проверен'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='tariff_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки тарифа'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='tariff_checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Проверил'),
        ),
    ]
