# Generated by Django 5.0.6 on 2026-02-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_orderproduct_tariff_checked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Архивный'),
        ),
    ]
