# Generated by Django 5.0.6 on 2026-04-10 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_product_archived'),
        ('plan', '0009_add_product_production_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='production_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='plan.producttype', verbose_name='Тип изделия (для планирования)'),
        ),
    ]
