# Generated by Django 4.1.7 on 2023-03-31 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='piecework_wages',
            field=models.BooleanField(default=False, verbose_name='В отделе установлена сдельная оплата труда'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата проведения')),
                ('transaction_type', models.CharField(choices=[('cash', 'Выдача НАЛ'), ('card', 'Выдача на карту'), ('tax', 'Налог'), ('accrual', 'Начисление'), ('debiting', 'Списание')], default='cash', max_length=50, verbose_name='Тип')),
                ('details', models.CharField(choices=[('purchase', 'Чек/Закупка'), ('wages', 'ЗП'), ('prize', 'Премия'), ('fine', 'Штраф'), ('loan', 'Займ')], default='wages', max_length=50, verbose_name='Детализация')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Сумма')),
                ('employee', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_employee', to=settings.AUTH_USER_MODEL, verbose_name='Получил')),
                ('executor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_executor', to=settings.AUTH_USER_MODEL, verbose_name='Провел')),
                ('inspector', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_inspector', to=settings.AUTH_USER_MODEL, verbose_name='Проверяющий')),
            ],
            options={
                'verbose_name': 'Финансовые транзакция',
                'verbose_name_plural': 'Финансовые транзакции',
            },
        ),
    ]
