# Generated by Django 4.1.7 on 2023-08-09 12:36

from django.db import migrations, models
import staff.service


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='color',
            field=models.CharField(default='#ffffff', max_length=9, validators=[staff.service.validate_color]),
        ),
    ]
