# Generated by Django 4.1.7 on 2023-08-28 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_department_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='commit_date',
        ),
        migrations.AddField(
            model_name='employee',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 28, 10, 47, 31, 458871), verbose_name='Дата / Время создания'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ending_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='inspect_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата / Время визирования'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='starting_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='details',
            field=models.CharField(choices=[('purchase', 'Чек/Закупка'), ('wages', 'ЗП'), ('prize', 'Премия'), ('fine', 'Штраф'), ('loan', 'Займ'), ('other', 'Другое')], default='wages', max_length=50, verbose_name='Детализация'),
        ),
    ]
