# Generated by Django 4.1.7 on 2023-04-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_department_piecework_wages_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='employees', to='staff.department', verbose_name='Отделы'),
        ),
    ]
