# Generated by Django 4.1.7 on 2023-04-26 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_employee_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата / Время действия')),
                ('audit_type', models.CharField(choices=[('error', 'Ошибка'), ('edit', 'Изменения'), ('authentication', 'Аутентификация'), ('other', 'Другое')], max_length=250, verbose_name='Тип события')),
                ('details', models.TextField(max_length=5000, verbose_name='Детали')),
                ('employee', models.ForeignKey(default='edit', on_delete=django.db.models.deletion.CASCADE, related_name='audits', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Действие пользователя',
                'verbose_name_plural': 'Действия пользователей',
            },
        ),
    ]
