# Generated by Django 4.1.7 on 2023-08-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_remove_transaction_commit_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата / Время создания'),
        ),
    ]
