# Generated by Django 4.1.7 on 2023-09-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_employee_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='details',
            field=models.CharField(choices=[('purchase', 'Чек/Закупка'), ('wages', 'ЗП'), ('prize', 'Премия'), ('fine', 'Штраф'), ('loan', 'Займ'), ('adjustment', 'Корректировка'), ('other', 'Другое')], default='wages', max_length=50, verbose_name='Детализация'),
        ),
    ]
