# Generated by Django 4.1.7 on 2023-11-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_alter_transaction_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='patronymic',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Отчество'),
        ),
    ]
