# Generated by Django 5.0.6 on 2024-06-25 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_employee_patronymic'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='boss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boss_for', to=settings.AUTH_USER_MODEL, verbose_name='Кому подчиняется'),
        ),
    ]
