# Generated by Django 5.0.6 on 2024-06-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_employee_boss'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_industrial',
            field=models.BooleanField(blank=True, default=True, verbose_name='Отдел производственный'),
        ),
    ]
