# Generated by Django 5.0.6 on 2024-06-28 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_department_is_industrial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='permanent_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_permanent', to='staff.department'),
        ),
    ]
