# Generated by Django 5.0.6 on 2024-07-08 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_employee_permanent_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='favorite_users',
            field=models.ManyToManyField(blank=True, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Избранные пользователи'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='current_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_current', to='staff.department', verbose_name='Текущий отдел'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='permanent_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_permanent', to='staff.department', verbose_name='Постоянный отдел'),
        ),
    ]
