# Generated by Django 5.0.6 on 2024-10-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_employee_favorite_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='piecework_wages',
            field=models.BooleanField(default=True, verbose_name='Сдельная форма оплаты труда'),
        ),
    ]
