# Generated by Django 5.0.6 on 2024-10-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_employee_piecework_wages'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='target_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата / Время прикрепления'),
        ),
    ]
