# Generated by Django 5.0.6 on 2024-10-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_transaction_target_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='created_automatically',
            field=models.BooleanField(default=True),
        ),
    ]
