# Generated by Django 5.0.6 on 2024-10-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_transaction_created_automatically'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='attention',
            field=models.BooleanField(default=False),
        ),
    ]
