# Generated by Django 5.0.6 on 2025-04-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_employee_attention'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Сортировка'),
        ),
    ]
