# Generated by Django 5.0.6 on 2025-04-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0016_department_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='kpd',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='КПД Сотрудника'),
        ),
    ]
