# Generated by Django 5.0.6 on 2025-07-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0017_employee_kpd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='current_balance',
        ),
        migrations.AddField(
            model_name='employee',
            name='piecework_amound',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Тариф в час'),
        ),
    ]
