# Generated by Django 5.0.6 on 2025-07-30 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0018_remove_employee_current_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='piecework_amound',
            new_name='piecework_amount',
        ),
    ]
