# Generated by Django 5.0.6 on 2025-08-11 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0019_rename_piecework_amound_employee_piecework_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
