# Generated by Django 5.0.6 on 2025-08-14 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0020_delete_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
