# Generated by Django 5.0.6 on 2025-09-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0021_alter_employee_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='api_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='API ID'),
        ),
    ]
