employees = {
    'Kharchenko_D': {
        'first_name': 'Дмитрий',
        'last_name': 'Харченко',
        'pin_code': 331331,
        'password': 'Dmitriy_852',
        'departments': [
            'Конструктора',
            'Обивка',
            'Пошив',
            'ППУ',
            'Крой',
            'Лазер',
            'Сборка',
            'Столярка',
            'Малярка',
            'Упаковка',
            'Подрядчики',
            'Пила',
        ],
        'groups': [
            'Визирование нарядов',
            'Режим просмотра бригадира',
            'Действия от имени сотрудников отдела',
            'Страница ЭЛО',
            'Администраторы',
            'Страница тарификаций',
            'Первичная тарификация',
            'Подтверждение тарификаций',
        ],
    },
    'root': {
        'first_name': 'Администратор',
        'last_name': '',
        'pin_code': 147858,
        'password': 'RLcb!!Dk',
        'departments': [
            'Конструктора',
            'Обивка',
            'Пошив',
            'ППУ',
            'Крой',
            'Лазер',
            'Сборка',
            'Столярка',
            'Малярка',
            'Упаковка',
            'Подрядчики',
            'Пила',
        ],
        'groups': [
            'Визирование нарядов',
            'Режим просмотра бригадира',
            'Действия от имени сотрудников отдела',
            'Страница ЭЛО',
            'Администраторы',
            'Страница тарификаций',
            'Первичная тарификация',
            'Подтверждение тарификаций', ],
    },
    'Kharkov_I': {
        'first_name': 'Илья',
        'last_name': 'Харьков',
        'pin_code': 789453,
        'password': 'Ilia_453',
        'departments': ['Конструктора'],
        'groups': [
            'Страница ЭЛО',
            'Режим просмотра бригадира',
            'Действия от имени сотрудников отдела',
        ],
    },
    'Velikiy_D': {
        'first_name': 'Денис',
        'last_name': 'Великий',
        'pin_code': 658651,
        'password': 'Denis_651',
        'departments': ['Столярка', 'Малярка', 'Лазер', ],
        'groups': [
            'Страница ЭЛО',
            'Визирование нарядов',
            'Режим просмотра бригадира',
            'Действия от имени сотрудников отдела',
            'Страница тарификаций',
            'Первичная тарификация',
        ],
    },
    'Gukov_O': {
        'first_name': 'Олег',
        'last_name': 'Гуков',
        'pin_code': 426486,
        'password': 'Oleg_486',
        'departments': ['Сборка', 'Пила'],
        'groups': [
            'Страница ЭЛО',
            'Визирование нарядов',
            'Режим просмотра бригадира',
            'Действия от имени сотрудников отдела',
            'Страница тарификаций',
            'Первичная тарификация',
        ],
    },
    'Shvetsova_T': {
        'first_name': 'Татьяна',
        'last_name': 'Швецова',
        'pin_code': 110304,
        'password': 'Tatiana_304',
        'departments': ['Крой', 'Пошив'],
        'groups': [
            'Страница ЭЛО',
            'Визирование нарядов',
            'Режим просмотра бригадира',
            'Действия от имени сотрудников отдела',
            'Страница тарификаций',
            'Первичная тарификация',
        ],
    },
    'Krechetov_O': {
        'first_name': 'Олег',
        'last_name': 'Кречетов',
        'pin_code': 362357,
        'password': 'Oleg_357',
        'departments': ['Обивка', 'ППУ', 'Упаковка'],
        'groups': [
            'Страница ЭЛО',
            'Визирование нарядов',
            'Режим просмотра бригадира',
            'Действия от имени сотрудников отдела',
            'Страница тарификаций',
            'Первичная тарификация',
        ],
    },
    'Ozhigin_D': {
        'first_name': 'Дмитрий',
        'last_name': 'Ожигин',
        'pin_code': 878622,
        'password': 'Dmitriy_622',
        'departments': [],
        'groups': [],
    },
    'Sulim_V': {
        'first_name': 'Вадим',
        'last_name': 'Сулим',
        'pin_code': 594281,
        'password': 'Vadim_281',
        'departments': ['Подрядчики', 'Лазер'],
        'groups': [
            'Страница ЭЛО',
            'Визирование нарядов',
            'Режим просмотра бригадира',
            'Действия от имени сотрудников отдела',
        ],
    },
    'Sapachuk_E': {
        'first_name': 'Елизавета',
        'last_name': 'Сапачук',
        'pin_code': 594141,
        'password': 'Elizabeth_141',
        'departments': ['Конструктора'],
        'groups': [
            'Страница ЭЛО',
        ],
    },
    'Kamalov_V': {
        'first_name': 'Владимир',
        'last_name': 'Камалов',
        'pin_code': 528142,
        'password': 'Vladimir_142',
        'departments': ['Лазер'],
        'groups': [
            'Страница ЭЛО',
        ],
    },
    'Korobejnikova_A': {
        'first_name': 'Анастасия',
        'last_name': 'Коробейникова',
        'pin_code': 128152,
        'password': 'Anastasia_152',
        'departments': ['Крой', 'Пошив'],
        'groups': [
            'Страница ЭЛО',
        ],
    },
    'Reviakina_O': {
        'first_name': 'Ольга',
        'last_name': 'Ревякина',
        'pin_code': 863177,
        'password': 'Olga_177',
        'departments': ['Крой', 'Пошив'],
        'groups': [
            'Страница ЭЛО',
        ],
    },
    'Semenova_O': {
        'first_name': 'Ольга',
        'last_name': 'Семенова',
        'pin_code': 256778,
        'password': 'Olga_778',
        'departments': ['Крой', 'Пошив'],
        'groups': [
            'Страница ЭЛО',
        ],
    },
    'Malahova_L': {
        'first_name': 'Лариса',
        'last_name': 'Малахова',
        'pin_code': 996754,
        'password': 'Larisa_754',
        'departments': ['Крой', 'Пошив'],
        'groups': [
            'Страница ЭЛО',
        ],
    },
    'Samsonov_M': {
        'first_name': 'Михаил',
        'last_name': 'Самсонов',
        'pin_code': 922753,
        'password': 'Mihail_753',
        'departments': ['Лазер'],
        'groups': [
            'Страница ЭЛО',
        ],
    },
    'Filatov_V': {
        'first_name': 'Владимир',
        'last_name': 'Филатов',
        'pin_code': 166842,
        'password': 'Vladimir_842',
        'departments': ['Пила'],
        'groups': [
            'Страница ЭЛО',
        ],
    },
    'Kashtanov_D': {
        'first_name': 'Дмитрий',
        'last_name': 'Каштанов',
        'pin_code': 986432,
        'password': 'Dmitriy_432',
        'departments': ['Сборка'],
        'groups': [
            'Страница ЭЛО',
        ],
    },
    'Berezin_E': {
        'first_name': 'Евгений',
        'last_name': 'Березин',
        'pin_code': 251369,
        'password': 'Evgeniy_369',
        'departments': ['Пила'],
        'groups': [
            'Страница ЭЛО',
        ],
    },
    'Postnikov_E': {
        'first_name': 'Евгений',
        'last_name': 'Постников',
        'pin_code': 474753,
        'password': 'Evgeniy_753',
        'departments': ['Сборка'],
        'groups': [
            'Страница ЭЛО',
        ],
    },
    'Ericojnen_B': {
        'first_name': 'Борис',
        'last_name': 'Эрикойнен',
        'pin_code': 728746,
        'password': 'Boris_746',
        'departments': ['Сборка'],
        'groups': [
            'Страница ЭЛО',
        ],
    },
    'Kotenev_S': {
        'first_name': 'Станислав',
        'last_name': 'Котенев',
        'pin_code': 121189,
        'password': 'Boris_189',
        'departments': ['Сборка'],
        'groups': [
            'Страница ЭЛО',
        ],
    },
    'Ilkaev_M': {
        'first_name': 'Михаил',
        'last_name': 'Илькаев',
        'pin_code': 858786,
        'password': 'Mihail_786',
        'departments': ['Сборка'],
        'groups': [
            'Страница ЭЛО',
        ],
    },
    'Absalyamov_Y': {
        'first_name': 'Юрий',
        'last_name': 'Абсалямов',
        'pin_code': 122353,
        'password': 'Yuri_353',
        'departments': ['Столярка'],
        'groups': [
            'Страница ЭЛО',
        ],
    },
    'Zaychenko_I': {
        'first_name': 'Илья',
        'last_name': 'Заиченко',
        'pin_code': 552363,
        'password': 'Ilia_363',
        'departments': ['Столярка'],
        'groups': [
            'Страница ЭЛО',
        ],
    },
    'Cheremuhin_A': {
        'first_name': 'Андрей',
        'last_name': 'Черемухин',
        'pin_code': 332411,
        'password': 'Andrey_411',
        'departments': ['Столярка'],
        'groups': [
            'Страница ЭЛО',
        ],
    },
    'Borodin_Y': {
        'first_name': 'Ярослав',
        'last_name': 'Бородин',
        'pin_code': 774545,
        'password': 'Yaroslav_545',
        'departments': ['Столярка'],
        'groups': [
            'Страница ЭЛО',
        ],
    },
    'Popov_D': {
        'first_name': 'Денис',
        'last_name': 'Попов',
        'pin_code': 333522,
        'password': 'Denis_522',
        'departments': ['Столярка', 'Малярка'],
        'groups': [
            'Страница ЭЛО',
        ],
    },
    'Kharitinov_I': {
        'first_name': 'Иван',
        'last_name': 'Харитонов',
        'pin_code': 454511,
        'password': 'Ivan_511',
        'departments': ['Обивка'],
        'groups': [
            'Страница ЭЛО',
        ],
    },
    'Egorov_A': {
        'first_name': 'Антон',
        'last_name': 'Егоров',
        'pin_code': 452226,
        'password': 'Anton_226',
        'departments': ['ППУ'],
        'groups': [
            'Страница ЭЛО',
        ],
    },
    'Levchenko_D': {
        'first_name': 'Дмитрий',
        'last_name': 'Левченко',
        'pin_code': 177475,
        'password': 'Dmitriy_475',
        'departments': ['ППУ'],
        'groups': [
            'Страница ЭЛО',
        ],
    },
    'Vinogradov_A': {
        'first_name': 'Артем',
        'last_name': 'Виноградов',
        'pin_code': 586963,
        'password': 'Artem_963',
        'departments': ['Упаковка'],
        'groups': [
            'Страница ЭЛО',
        ],
    },
    'Yuldashev_S': {
        'first_name': 'Саид',
        'last_name': 'Юлдашев',
        'pin_code': 203569,
        'password': 'Said_569',
        'departments': ['Упаковка'],
        'groups': [
            'Страница ЭЛО',
        ],
    },
    'Batirov_B': {
        'first_name': 'Бобирбек',
        'last_name': 'Батиров',
        'pin_code': 305069,
        'password': 'Bobirbek_069',
        'departments': ['Упаковка'],
        'groups': [
            'Страница ЭЛО',
        ],
    },
    'Askerov_E': {
        'first_name': 'Эдуард',
        'last_name': 'Аскеров',
        'pin_code': 230256,
        'password': 'Eduard_256',
        'departments': ['Упаковка'],
        'groups': [
            'Страница ЭЛО',
        ],
    },
    'Golubev_V': {
        'first_name': 'Валерий',
        'last_name': 'Голубев',
        'pin_code': 852036,
        'password': 'Valeriy_036',
        'departments': ['Обивка'],
        'groups': [
            'Страница ЭЛО',
        ],
    },
    'Krupen_A': {
        'first_name': 'Алексей',
        'last_name': 'Крупень',
        'pin_code': 255601,
        'password': 'Aleksei_601',
        'departments': ['Обивка'],
        'groups': [
            'Страница ЭЛО',
        ],
    },
    'Badulin_D': {
        'first_name': 'Даниил',
        'last_name': 'Бадулин',
        'pin_code': 748605,
        'password': 'Daniil_605',
        'departments': ['Обивка'],
        'groups': [
            'Страница ЭЛО',
        ],
    },
    'Prohorenko_D': {
        'first_name': 'Дмитрий',
        'last_name': 'Прохоренко',
        'pin_code': 963014,
        'password': 'Dmitriy_014',
        'departments': ['Обивка'],
        'groups': [
            'Страница ЭЛО',
        ],
    },
    'Gurenok_P': {
        'first_name': 'Гурёнок',
        'last_name': ' Павел',
        'pin_code': 411212,
        'password': 'Dmitriy_212',
        'departments': ['Обивка'],
        'groups': [
            'Страница ЭЛО',
        ],
    },
    'Petrov_V': {
        'first_name': 'Виталий',
        'last_name': ' Петров',
        'pin_code': 855457,
        'password': 'Vitaliy_457',
        'departments': ['Обивка'],
        'groups': [
            'Страница ЭЛО',
        ],
    },
    'Klishin_D': {
        'first_name': 'Денис',
        'last_name': 'Клишин',
        'pin_code': 112332,
        'password': 'Denis_332',
        'departments': ['Обивка'],
        'groups': [
            'Страница ЭЛО',
        ],
    },
    'Bukin_V': {
        'first_name': 'Владислав',
        'last_name': 'Букин',
        'pin_code': 202987,
        'password': 'Vladislav_987',
        'departments': ['Конструктора'],
        'groups': [
            'Страница ЭЛО',
        ],
    },
}
