employees = {
    'Kharchenko_D': {
        'first_name': 'Дмитрий',
        'last_name': 'Харченко',
        'pin_code': 331331,
        'password': 'Dmitriy_852',
        'departments': [
            'Конструктора',
            'Обивка',
            'Пошив',
            'ППУ',
            'Крой',
            'Лазер',
            'Сборка',
            'Столярка',
            'Малярка',
            'Упаковка',
            'Подрядчики',
            'Пила',
        ],
        'groups': ['Администраторы', 'Бригадиры'],
    },
    'root': {
        'first_name': 'Администратор',
        'last_name': '',
        'pin_code': 147858,
        'password': 'RLcb!!Dk',
        'departments': [
            'Конструктора',
            'Обивка',
            'Пошив',
            'ППУ',
            'Крой',
            'Лазер',
            'Сборка',
            'Столярка',
            'Малярка',
            'Упаковка',
            'Подрядчики',
            'Пила',
        ],
        'groups': ['Администраторы', 'Бригадиры'],
    },
    'Kharkov_I': {
        'first_name': 'Илья',
        'last_name': 'Харьков',
        'pin_code': 789453,
        'password': 'Ilia_453',
        'departments': ['Конструктора'],
        'groups': ['Работники'],
    },
    'Velikiy_D': {
        'first_name': 'Денис',
        'last_name': 'Великий',
        'pin_code': 658651,
        'password': 'Denis_651',
        'departments': ['Столярка', 'Малярка', 'Лазер', ],
        'groups': ['Бригадиры'],
    },
    'Gukov_O': {
        'first_name': 'Олег',
        'last_name': 'Гуков',
        'pin_code': 426486,
        'password': 'Oleg_486',
        'departments': ['Сборка', 'Пила'],
        'groups': ['Бригадиры'],
    },
    'Shvetsova_T': {
        'first_name': 'Татьяна',
        'last_name': 'Швецова',
        'pin_code': 110304,
        'password': 'Tatiana_304',
        'departments': ['Крой', 'Пошив'],
        'groups': ['Бригадиры'],
    },
    'Krechetov_O': {
        'first_name': 'Олег',
        'last_name': 'Кречетов',
        'pin_code': 362357,
        'password': 'Oleg_357',
        'departments': ['Обивка', 'ППУ'],
        'groups': ['Бригадиры'],
    },
    'Ozhigin_D': {
        'first_name': 'Дмитрий',
        'last_name': 'Ожигин',
        'pin_code': 878622,
        'password': 'Dmitriy_622',
        'departments': ['Упаковка'],
        'groups': ['Бригадиры'],
    },
    'Sulim_V': {
        'first_name': 'Вадим',
        'last_name': 'Сулим',
        'pin_code': 594281,
        'password': 'Vadim_281',
        'departments': ['Подрядчики'],
        'groups': ['Бригадиры'],
    },
}
