events {
    worker_connections 1024;
}

http {
    gzip on;
    gzip_comp_level 6;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    include /etc/nginx/mime.types;

    server {
        listen 80;
        listen [::]:80;

        server_name elo.szmk.pro;

        # Редирект с HTTP на HTTPS
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name elo.szmk.pro;

        ssl_certificate /etc/nginx/ssl/elo.szmk.pro.csr;
        ssl_certificate_key /etc/nginx/ssl/elo.szmk.pro.key;

        ssl_prefer_server_ciphers on;
        ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";

        root /usr/share/nginx/html;
        index index.html;

        location /media {
            alias /usr/share/nginx/html/media;
        }

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
