# Generated by Django 5.0.6 on 2024-06-15 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0007_employee_patronymic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, verbose_name='Когда создана')),
                ('status', models.CharField(blank=True, choices=[('1', 'Ожидает'), ('2', 'В работе'), ('3', 'Готова'), ('4', 'Отменена')], default='1', max_length=50, verbose_name='Статус')),
                ('urgency', models.CharField(blank=True, choices=[('1', 'Низкая'), ('2', 'Обычная'), ('3', 'Важная'), ('4', 'Горящая')], default='2', max_length=50, verbose_name='Срочность')),
                ('view_mode', models.CharField(blank=True, choices=[('1', 'Только мне'), ('2', 'Видна отделу'), ('3', 'Видна всем')], default='1', max_length=50, verbose_name='Видимость')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Описание')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Крайний срок')),
                ('ready_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда готова')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда завизирована')),
                ('appointed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointed_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Кем назначена')),
                ('co_executors', models.ManyToManyField(related_name='co_executors_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Соисполнители')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executor_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('for_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.department', verbose_name='Видна в отделе')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='TaskImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_filename', models.CharField(blank=True, max_length=240, null=True, verbose_name='Имя файла')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/tasks/', verbose_name='Ссылка на изображение')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images/tasks/thumbnails/', verbose_name='Миниатюра')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_images', to='tasks.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Изображение задачи',
                'verbose_name_plural': 'Изображения задач',
            },
        ),
    ]
