# Generated by Django 5.0.6 on 2024-06-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Когда создана'),
        ),
    ]
