# Generated by Django 5.0.6 on 2024-06-25 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='task',
            name='appointed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда назначена'),
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Кем создана'),
        ),
        migrations.AlterField(
            model_name='task',
            name='appointed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointed_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Кем назначена'),
        ),
        migrations.AlterField(
            model_name='task',
            name='view_mode',
            field=models.CharField(blank=True, choices=[('1', 'Только мне'), ('2', 'Видна отделу'), ('3', 'Видна всем'), ('4', 'Мне и исполнителям')], default='1', max_length=50, verbose_name='Видимость'),
        ),
    ]
