# Generated by Django 5.0.6 on 2024-07-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_employee_favorite_users_and_more'),
        ('tasks', '0004_rename_created_task_created_at_task_appointed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='execution_comment',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Комментарий к выполнению'),
        ),
        migrations.AddField(
            model_name='task',
            name='for_departments',
            field=models.ManyToManyField(blank=True, related_name='tasks_for_department', to='staff.department', verbose_name='Видна в отделах'),
        ),
    ]
