# Generated by Django 5.0.6 on 2024-08-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_taskviewinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskcomment',
            options={'ordering': ['-add_date'], 'verbose_name': 'Комментарий к задаче', 'verbose_name_plural': 'Комментарии к задачам'},
        ),
        migrations.AlterField(
            model_name='taskviewinfo',
            name='last_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата просмотра'),
        ),
    ]
