# Generated by Django 5.0.6 on 2024-08-30 13:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_taskcomment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='amount',
        ),
        migrations.AlterField(
            model_name='task',
            name='appointed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointed_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Кем назначена'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Кем создана'),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_comment_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.CreateModel(
            name='TaskExecutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Сумма/Вознаграждение')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_executor', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_executor', to='tasks.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
                'unique_together': {('employee', 'task')},
            },
        ),
        migrations.AddField(
            model_name='task',
            name='new_co_executors',
            field=models.ManyToManyField(related_name='task_new_co_executors', to='tasks.taskexecutor', verbose_name='Соисполнители'),
        ),
        migrations.AddField(
            model_name='task',
            name='new_executor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_new_executor', to='tasks.taskexecutor', verbose_name='Исполнитель'),
        ),
        migrations.CreateModel(
            name='TaskTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Сумма')),
                ('add_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата добавления')),
                ('comment', models.CharField(blank=True, max_length=250, null=True, verbose_name='Комментарий')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_created_tariffs', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_tariffs', to='tasks.task', verbose_name='Задача')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='confirmed_tariff',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_confirmed_tariff', to='tasks.tasktariff', verbose_name='Утвержденный тариф'),
        ),
        migrations.AddField(
            model_name='task',
            name='proposed_tariff',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_proposed_tariff', to='tasks.tasktariff', verbose_name='Предложенный тариф'),
        ),
    ]
