# Generated by Django 5.0.6 on 2024-09-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_remove_task_amount_alter_task_appointed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskimage',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/tasks/', verbose_name='Ссылка на изображение'),
        ),
    ]
