# Generated by Django 5.0.6 on 2024-09-17 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_taskimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskimage',
            options={'ordering': ['-id'], 'verbose_name': 'Изображение задачи', 'verbose_name_plural': 'Изображения задач'},
        ),
    ]
