# Generated by Django 5.0.6 on 2024-09-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_taskimage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='appointed_by_boss',
            field=models.BooleanField(blank=True, default=False, verbose_name='Назначен бригадиром'),
        ),
    ]
