# Generated by Django 5.0.6 on 2025-07-21 10:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_task_appointed_by_boss'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='co_executors',
            field=models.ManyToManyField(blank=True, related_name='co_executors_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Соисполнители'),
        ),
        migrations.AlterField(
            model_name='task',
            name='new_co_executors',
            field=models.ManyToManyField(blank=True, related_name='task_new_co_executors', to='tasks.taskexecutor', verbose_name='Соисполнители'),
        ),
    ]
