save ""

appendonly no

stop-writes-on-bgsave-error no

dir /data

# Оптимизация памяти
maxmemory 512mb
maxmemory-policy allkeys-lru

# Оптимизация производительности
tcp-backlog 511
timeout 300
tcp-keepalive 60

# Лимиты соединений
maxclients 1000
