# Generated by Django 5.0.6 on 2026-02-02 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео'), ('audio', 'Звуковое сообщение'), ('text', 'Текстовая заметка')], max_length=10, verbose_name='Тип заметки')),
                ('file', models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/%d/', verbose_name='Файл')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текстовая заметка')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='attachments_content_44d952_idx')],
            },
        ),
    ]
