# Generated by Django 5.0.6 on 2026-02-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attachment',
            new_name='attachments_content_9ba9de_idx',
            old_name='attachments_content_44d952_idx',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='content_type',
            field=models.CharField(blank=True, choices=[('product', 'Продукт'), ('order', 'Заказ'), ('task', 'Задача')], max_length=20, null=True, verbose_name='Тип сущности'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='object_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID сущности'),
        ),
    ]
