# Generated by Django 5.0.6 on 2026-02-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_rename_attachments_content_44d952_idx_attachments_content_9ba9de_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='url',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='type',
            field=models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео'), ('audio', 'Звуковое сообщение'), ('text', 'Текстовая заметка'), ('file', 'Файл')], max_length=10, verbose_name='Тип заметки'),
        ),
    ]
