# Generated by Django 5.0.6 on 2026-02-02 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0003_remove_attachment_url_alter_attachment_type'),
        ('staff', '0022_employee_api_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.department', verbose_name='Отдел'),
        ),
    ]
