# Generated by Django 5.0.6 on 2025-07-17 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, unique=True, verbose_name='Наименование')),
                ('state', models.CharField(blank=True, choices=[('1', 'Начисление'), ('2', 'Проверка'), ('3', 'Бюджет'), ('4', 'К выплате'), ('5', 'Выплата'), ('6', 'Закрыта')], max_length=250, null=True, verbose_name='Статус')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='Период с')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Период по')),
                ('cash_payout', models.IntegerField(default=0, verbose_name='Согласованная сумма к выдаче')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Период закрыт')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('crated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Ведомость',
                'verbose_name_plural': 'Ведомости',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='Дата закрепления')),
                ('amount', models.IntegerField(default=0, verbose_name='Сумма')),
                ('earning_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('earning_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий зарплатный')),
                ('approval_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earnings_approved', to=settings.AUTH_USER_MODEL, verbose_name='Кто согласовал')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earnings_created', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earnings', to=settings.AUTH_USER_MODEL, verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Начисление',
                'verbose_name_plural': 'Начисления',
                'ordering': ['-target_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('start_balance', models.IntegerField(blank=True, default=0, null=True, verbose_name='Баланс на начало периода')),
                ('cash_payout', models.IntegerField(default=0, verbose_name='Сумма к выдаче НАЛ')),
                ('cash_approval', models.BooleanField(default=False, verbose_name='Сумма к выдаче НАЛ согласована')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Блокировка начислений')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Период закрыт')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salary.payroll', verbose_name='Ведомость')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_rows', to=settings.AUTH_USER_MODEL, verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Позиция ведомости',
                'verbose_name_plural': 'Позиции ведомостей',
                'ordering': ['-id'],
                'unique_together': {('payroll', 'user')},
            },
        ),
    ]
