# Generated by Django 5.0.6 on 2025-07-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='earning',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='Не редактируемый'),
        ),
    ]
