# Generated by Django 5.0.6 on 2025-07-31 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_earning_is_locked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='earning',
            old_name='crated_at',
            new_name='created_at',
        ),
    ]
