# Generated by Django 5.0.6 on 2025-07-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0003_rename_crated_at_earning_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earning',
            name='target_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата закрепления'),
        ),
    ]
