# Generated by Django 5.0.6 on 2025-07-31 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0004_alter_earning_target_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='earning',
            name='cash_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 7, 31, 12, 2, 27, 997123), null=True, verbose_name='Дата добавления'),
        ),
    ]
