# Generated by Django 5.0.6 on 2025-07-31 12:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0005_earning_cash_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earning',
            name='cash_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата добавления'),
        ),
    ]
