# Generated by Django 5.0.6 on 2025-08-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0007_alter_earning_cash_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrow',
            name='card_payout',
            field=models.IntegerField(default=0, verbose_name='Сумма к выдаче НАЛ'),
        ),
        migrations.AddField(
            model_name='payrollrow',
            name='ip_payout',
            field=models.IntegerField(default=0, verbose_name='Сумма к выдаче НАЛ'),
        ),
        migrations.AddField(
            model_name='payrollrow',
            name='loan_payout',
            field=models.IntegerField(default=0, verbose_name='Сумма к выдаче НАЛ'),
        ),
        migrations.AddField(
            model_name='payrollrow',
            name='tax_payout',
            field=models.IntegerField(default=0, verbose_name='Сумма к выдаче НАЛ'),
        ),
    ]
