# Generated by Django 5.0.6 on 2025-09-09 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0008_payrollrow_card_payout_payrollrow_ip_payout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollrow',
            name='start_balance',
        ),
    ]
