# Generated by Django 5.0.6 on 2025-12-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0009_remove_payrollrow_start_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='state',
            field=models.CharField(blank=True, choices=[('0', 'Создана'), ('1', 'Подсчет ЗП'), ('2', 'Виза'), ('3', 'Бюджет'), ('4', 'К выплате'), ('5', 'Выплата'), ('6', 'Закрыта')], max_length=250, null=True, verbose_name='Статус'),
        ),
    ]
