FROM postgres:15.2-alpine

EXPOSE 5432

COPY entrypoint.sh /usr/local/bin/entrypoint.sh

RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

USER postgres

CMD ["postgres"]